/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'status' : string,
  'doctorId' : bigint,
  'deleted' : boolean,
  'patientId' : bigint,
  'date' : string,
  'time' : string,
  'lastUpdate' : Time,
  'notes' : string,
}
export interface DashboardTotals {
  'totalPatients' : bigint,
  'todaysAppointments' : bigint,
  'totalDoctors' : bigint,
  'totalAppointments' : bigint,
}
export interface Doctor {
  'id' : bigint,
  'patientIds' : Array<bigint>,
  'deleted' : boolean,
  'name' : string,
  'lastUpdate' : Time,
  'availability' : boolean,
  'specialization' : string,
  'department' : string,
}
export interface Patient {
  'id' : bigint,
  'age' : bigint,
  'deleted' : boolean,
  'contact' : string,
  'admissionDate' : string,
  'name' : string,
  'treatment' : string,
  'lastUpdate' : Time,
  'gender' : string,
  'disease' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelAppointment' : ActorMethod<[bigint], undefined>,
  'createAppointment' : ActorMethod<[Appointment], bigint>,
  'createDoctor' : ActorMethod<[Doctor], bigint>,
  'createPatient' : ActorMethod<[Patient], bigint>,
  'deleteDoctor' : ActorMethod<[bigint], undefined>,
  'deletePatient' : ActorMethod<[bigint], undefined>,
  'getAdmissionsByDate' : ActorMethod<[], Array<[string, bigint]>>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllDoctors' : ActorMethod<[], Array<Doctor>>,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getAppointmentsByDoctor' : ActorMethod<[bigint], Array<Appointment>>,
  'getAppointmentsByPatient' : ActorMethod<[bigint], Array<Appointment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardTotals' : ActorMethod<[string], DashboardTotals>,
  'getDiseaseFrequency' : ActorMethod<[], Array<[string, bigint]>>,
  'getDoctorAppointmentCounts' : ActorMethod<[], Array<[bigint, bigint]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'readDoctor' : ActorMethod<[bigint], Doctor>,
  'readPatient' : ActorMethod<[bigint], Patient>,
  'rescheduleAppointment' : ActorMethod<[bigint, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateDoctor' : ActorMethod<[Doctor], undefined>,
  'updatePatient' : ActorMethod<[Patient], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];